### ISSUE TITLE
codde

### ISSUE THREAD

**Issue by nandagozalio** [gymie/belajar-laravel#15]
![Screenshot_3](https://user-images.githubusercontent.com/55728647/66730016-17d80f80-ee79-11e9-9548-246c84fbdde7.png)

**Comment by gymie** [comment]
@foreach ($data as $item)
                    <tr>
                        <td>{{ $item->desc }}</td>
                        <td><div class="badge badge-pill
                            {{ $item->status==1?"badge-success":"badge-danger" }}
                            p-2">{{ $item->status==1?"Selesai":"Belum Selesai" }}</div></td>
                        <td><a href="" class="btn btn-warning btn-block">Selesai</a></td>
                        <td><a href="" class="btn btn-danger btn-block">Hapus</a></td>
                    </tr>
                @endforeach

**Comment by gymie** [comment]
@foreach ($data as $item)
                    <tr>
                        <td>{{ $item->desc }}</td>
                        <td><div class="badge badge-pill
                            {{ $item->status==1?"badge-success":"badge-danger" }}
                            p-2">{{ $item->status==1?"Selesai":"Belum Selesai" }}</div></td>
                        <td><a href="" class="btn btn-warning btn-block">Selesai</a></td>
                        <td><a href="" class="btn btn-danger btn-block">Hapus</a></td>
                    </tr>
                @endforeach
