### ISSUE TITLE
Tidak tampil table database ke web

### ISSUE THREAD

**Issue by agis-syah** [gymie/belajar-laravel#16]
![tidaknampil](https://user-images.githubusercontent.com/55725736/66730007-0ee73e00-ee79-11e9-8621-78c71a920819.png)
![coding](https://user-images.githubusercontent.com/55725736/66730008-0ee73e00-ee79-11e9-9755-e5c25c8c0d13.png)

**Comment by gymie** [comment]
cek kembali isi tabel apakah ada data atau tidak
