### ISSUE TITLE
error: Target class [App\Http\Controllers\Todocontrollerform] does not exist.

### ISSUE THREAD

**Issue by Perwan** [gymie/belajar-laravel#18]
![Screenshot_3](https://user-images.githubusercontent.com/55711189/66730655-42c46280-ee7d-11e9-85fb-6e1dd7d18c9b.png)

**Comment by gymie** [comment]
di web.php cek kembali perintah dibawha ini 

    route::post('simpan','TodoController@simpanform')
    ->name('simpan.todo');
