### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation

### ISSUE THREAD

**Issue by nandagozalio** [gymie/belajar-laravel#19]
![Screenshot_5](https://user-images.githubusercontent.com/55728647/66730684-77d0b500-ee7d-11e9-97ce-810119a41656.png)

**Comment by gymie** [comment]
kolom desc pada form harus diisi atau tidak boleh kosong

**Comment by gymie** [comment]
cek kembali penamaan inputan pada form apakah sudah benar
    <div class="form-group">
            <label for="desc">Descriptions</label>
            <input type="text" class="form-control"
                name="description">
        </div>
