### ISSUE TITLE
error server laravel ketika clone di komputer lain

### ISSUE THREAD

**Issue by Natanaelsinurat** [gymie/belajar-laravel#5]
Waktu saya jalankan artisan serve di komputer saya, muncul error seperti ini
![error artisanserve](https://user-images.githubusercontent.com/55680725/66016447-e9fddd00-e500-11e9-9f3b-f2a2bda6f6bb.png)

**Comment by gymie** [comment]
karena folder vendor dan file .env tidak di push ke github.. maka anda harus menjalankan perintah untuk mendownload kembali folder vendor dengan perintah :

    composer install

sedangkan untuk file .env anda bisa mengcopy file .env.example menjadi file .env

    cp .env.example .env
    copy .env.example .env

setelah itu jalankan generate key untuk file .env dengan cara

    php artisan key:generate
