### ISSUE TITLE
Error : Target class [App\Http\Controllers\Todocontrollerform] does not exist.

### ISSUE THREAD

**Issue by Perwan** [gymie/belajar-laravel#8]
![Screenshot_2](https://user-images.githubusercontent.com/55711189/66020678-05251880-e512-11e9-9f42-51255c6f47d4.png)

**Comment by gymie** [comment]
sepertinya terjadi kesalahan pemanggilan method pada controller. yang ditulis

    Todocontrollerform

harusnya

    Todocontroller@form
