### ISSUE TITLE
pak ini tbltodo nya error gimana nih pak solusi nya

### ISSUE THREAD

**Issue by sudeshratch** [gymie/belajar-laravel#9]
![Screenshot_4](https://user-images.githubusercontent.com/55694500/66729430-992da300-ee75-11e9-935f-15ff7a7da071.png)

**Comment by gymie** [comment]
hal ini terjadi karena settingan alamat database .env tidak dirubah ke database yang benar?

jika ada perubahan file .env .. makan anda harus menjalankan / merestart kembali perintah

    php artisan serve
